export  const projects = [
  {
    title: "Dissonance",
    description: "A software that protects audio files from unauthorized AI training using adversarial perturbations—imperceptible to humans, disruptive to AI.",
    skills: ["Audio Security", "C++ Development", "Adversarial Machine Learning", "UI Prototyping"],
    tech: ["C++", "Python", "Django", "React"],
    repoLink: 'https://github.com/Dissonance-Eip',
    date: "March 2025 - June 2027",
  },
  {
    title: "Personal Portfolio",
    description: "This very website your on! A personal portfolio website showcasing my projects and skills.",
    skills: ["Web Development", "UI Design"],
    tech: ["React", "TailwindCSS", "JavaScript"],
    repoLink: 'https://github.com/nkurata/my-website',
    date: "Jan 2025",
  },
  {
    title: 'R-Type',
    description: 'A multiplayer space 2D shooter game with a client-server architecture & modular game engine.',
    skills: ['Networking', 'Game Development', 'Dynamic Libraries'],
    tech: ['C++', 'SFML', 'CMake'],
    repoLink: 'https://github.com/LucaMartinet7/R-Type',
    date: 'Nov 2024 - Jan 2025',
    context: 'Epitech Project',
  },
  {
    title: 'Neural Network',
    description: 'A neural network that predicts the outcome of a game.',
    skills: ['Machine Learning', 'Neural Networks'],
    tech: ['Python', 'MakeFile'],
    repoLink: 'https://github.com/LucaMartinet7/Neural-Network',
    date: 'Nov 2024 - Dec 2024',
    context: 'Epitech Project',
  },
  {
    title: 'AREA (Action Reaction)',
    description: 'A web application that allows users to automate tasks between different services.',
    skills : ['Web Development', 'APIs', 'Database Management', 'UI Design'],
    tech: ['Flutter', 'Dart', 'Django', 'Python'],
    repoLink: 'https://github.com/LucaMartinet7/Area-Tek3',
    date: 'Oct 2024 - Nov 2024',
    context: 'Epitech Project',
  },
  {
    title: 'Maze Game',
    description: 'A Python-based maze game using the turtle module.',
    skills: ['Game Development'],
    tech: ['Python'],
    repoLink: 'https://github.com/nkurata/MazeGame',
    date: 'Dec 2021',
    context: 'Personal Project',
  },
  {
    title: 'Ubuntu x86-64 Container',
    description: 'Docker container running Ubuntu on x86-64 architecture.',
    skills : ['Container', 'Linux', 'Architecture'],
    tech: ['Docker', 'Ubuntu', 'x86-64', 'Apple Silicon'],
    repoLink: 'https://github.com/nkurata/UbuntuContainer',
    date: 'Jan 2024',
    context: 'Personal Project',
  },
  {
    title: 'Minimal-OS',
    description: 'Minimalist prompt with Git status indicators.',
    skills: ['Shell Scripting'],
    tech: ['Oh My Zsh', 'Zsh', 'Shell'],
    repoLink: 'https://github.com/nkurata/zsh-theme',
    date: 'Jan 2023',
    context: 'Personal Project',
  },
  {
    title: 'Dynamic Game Engine',
    description: 'Play games with different graphic libraries at runtime.',
    skills: ['Game Development', 'Dynamic Libraries'],
    tech: ['C++', 'SFML', 'SDL-2', 'NCurses', 'MakeFile'],
    repoLink: 'https://github.com/nkurata/Arcarde',
    date: 'Mar 2024 - Apr 2024',
    context: 'Epitech Project',
  },
  {
    title: 'System Call Tracing Tool',
    description: 'Tracks and displays system calls made by a program.',
    skills : ['System Calls', 'Tracing', 'Operation Systems', 'Debugging'],
    tech: ['C', 'Unix', 'x86-64', 'MakeFile'],
    repoLink: 'https://github.com/nkurata/System-Call-Tracing-Tool',
    date: 'Mar 2024 - Apr 2024',
    context: 'Epitech Project',
  },
  {
    title: 'Binary File Analyzer',
    description: 'Recreates nm and objdump Unix tools.',
    skills: ['Binary Files', 'Parsing', 'Operation Systems'],
    tech: ['C', 'ELF', 'Unix', 'MakeFile'],
    repoLink: 'https://github.com/nkurata/Binary-File-Analyzer-and-Displayer.git',
    date: 'Feb 2024 - Mar 2024',
    context: 'Epitech Project',
  },
  {
    title: 'Circuit Simulator',
    description: 'Build a circuit simulator to understand digital circuits.',
    skills : ['Circuits', 'Logic Gates'],
    tech: ['C++', 'MakeFile'],
    repoLink: 'https://github.com/nkurata/Circuit-Simulator',
    date: 'Feb 2024 - Mar 2024',
    context: 'Epitech Project',
  },
  {
    title: 'Image Compressor',
    description: 'Reduces image file sizes with efficient algorithms.',
    skills: ['Compression', 'Image Processing'],
    tech: ['Haskell', 'MakeFile'],
    repoLink: 'https://github.com/nkurata/Image-Compressor',
    date: 'Feb 2024 - Mar 2024',
    context: 'Epitech Project',
  },
  {
    title: 'Portfolio Page',
    description: 'A landing page used as a Link page for an Artist.',
    skills: ['Web Development', 'UI Design'],
    tech: ['HTML', 'CSS', 'JavaScript'],
    repoLink: 'https://github.com/nkurata/WebisteCK',
    date: 'Mar 2024',
    context: 'Personal Project',
  },
  {
    title: 'File Transfer Protocol',
    description: 'Simplified FTP server and client.',
    skills: ['Networking', 'File Transfer'],
    tech: ['C', 'MakeFile'],
    repoLink: 'https://github.com/nkurata/File-Transfer-Protocol.git',
    date: 'Jan 2024 - Feb 2024',
    context: 'Epitech Project',
  },
  {
    title: 'Mini Lib C',
    description: 'Recreation of C Library in Assembly.',
    skills: ['Library', 'System Calls'],
    tech: ['x86 Assembly', 'C', 'MakeFile'],
    repoLink: 'https://github.com/nkurata/Mini-Lib-C.git',
    date: 'Jan 2024 - Feb 2024',
    context: 'Epitech Project',
  },
  {
    title: 'Makefile Generator',
    description: 'Automated Makefile generator.',
    skills: ['Automation', 'Scripting'],
    tech: ['Bash', 'MakeFile'],
    repoLink: 'https://github.com/nkurata/Automated-Makefile-Generator.git',
    date: 'Jul 2023',
    context: 'Epitech Project',
  },
  {
    title: 'AI-Pathfinding Simulation',
    description: 'Autonomous vehicle navigates through a virtual environment.',
    skills: ['AI', 'Pathfinding'],
    tech: ['Python', 'MakeFile'],
    repoLink: 'https://github.com/nkurata/AI-Powered-Pathfinding-Simulation.git',
    date: 'Apr 2023 - May 2023',
    context: 'Epitech Project',
  },
  {
    title: 'DevOps Tool',
    description: 'Streamlines deployment and CI.',
    skills: ['DevOps', 'CI/CD', 'Automation'],
    tech: ['GitHub', 'C', 'MakeFile', 'GitHub Workflows', 'MakeFile'],
    repoLink: 'https://github.com/nkurata/Chocolatin_CI',
    date: 'Mar 2023 - Apr 2023',
    context: 'Epitech Project',
  },
  {
    title: 'Square Finder',
    description: 'Finds the largest square on a 2D map.',
    skills: ['Algorithm Optimization', 'File Handling'],
    tech: ['C', 'MakeFile'],
    repoLink: 'https://github.com/nkurata/Largest-Square-Finder-on-2D-Map-BSQ.git',
    date: 'Oct 2022 - Dec 2022',
    context: 'Epitech Project',
  },
  {
    title: 'My RPG',
    description: '2D RPG game engine.',
    skills: ['Game Development', 'UI Design'],
    tech: ['C', 'SFML', 'MakeFile'],
    repoLink: 'https://github.com/nkurata/My-RPG.git',
    date: 'Mar 2023 - Apr 2023',
    context: 'Epitech Project',
  },
  {
    title: 'My Paint',
    description: 'Simple drawing application.',
    skills: ['UI Design', 'Graphics', 'MakeFile'],
    tech: ['C', 'SFML'],
    repoLink: 'https://github.com/nkurata/My-Paint.git',
    date: 'Feb 2023 - Mar 2023',
    context: 'Epitech Project',
  },
  {
    title: 'Minishell',
    description: 'Minimalistic shell with command execution.',
    skills: ['Shell Scripting', 'System Calls'],
    tech: ['C','Unix', 'Shell', 'MakeFile'],
    repoLink: 'https://github.com/nkurata/MiniShell.git',
    date: 'Feb 2023 - Apr 2023',
    context: 'Epitech Project',
  },
  {
    title: 'My Sokoban',
    description: 'Classic Sokoban puzzle game.',
    skills: ['Game Logic', 'Terminal Graphics'],
    tech: ['C', 'MakeFile'],
    repoLink: 'https://github.com/nkurata/My-Sokoban.git',
    date: 'Nov 2022 - Dec 2022',
    context: 'Epitech Project',
  },
  {
    title: 'Dante\'s Star',
    description: 'Generates and solves mazes.',
    skills: ['Algorithm Design', 'Maze Generation'],
    tech: ['C', 'MakeFile'],
    repoLink: 'https://github.com/nkurata/Dante-s-Star.git',
    date: 'Jan 2023 - Mar 2023',
    context: 'Epitech Project',
  },
  {
    title: 'My Printf',
    description: 'Recreates the printf function in C.',
    skills: ['System Calls', 'String Manipulation', 'Output Handling'],
    tech: ['C', 'MakeFile'],
    repoLink: 'https://github.com/nkurata/My-Printf.git',
    date: 'Oct 2022 - Nov 2022',
    context: 'Epitech Project',
  }
];