export const tech = {
  'C++': 'https://upload.wikimedia.org/wikipedia/commons/1/18/ISO_C%2B%2B_Logo.svg',
  'SFML': 'https://www.sfml-dev.org/download/goodies/sfml-icon-big.png',
  'Python': 'https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg',
  'Flutter': 'https://storage.googleapis.com/cms-storage-bucket/0dbfcc7a59cd1cf16282.png',
  'Dart': 'https://upload.wikimedia.org/wikipedia/commons/7/7e/Dart-logo.png',
  'Django': 'https://static.djangoproject.com/img/logos/django-logo-negative.png',
  'Docker': 'https://img.icons8.com/fluent/512/docker.png',
  'Ubuntu': 'https://assets.ubuntu.com/v1/29985a98-ubuntu-logo32.png',
  'x86-64': 'https://icons.iconarchive.com/icons/icons8/android/512/Computer-Hardware-X86-icon.png',
  'Apple Silicon': 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Apple_logo_grey.svg/404px-Apple_logo_grey.svg.png',
  'Oh My Zsh': 'https://ohmyz.sh/assets/img/logo.svg',
  'Zsh': 'https://img.icons8.com/ios-filled/512/console.png',
  'Shell': 'https://img.icons8.com/ios/512/command-line.png',
  'SDL-2': 'https://www.libsdl.org/media/SDL_logo.png',
  'NCurses': 'https://cdn.changelog.com/uploads/icons/topics/Z3e/icon_large.png?v=63714708682',
  'C': 'https://upload.wikimedia.org/wikipedia/commons/1/19/C_Logo.png',
  'Unix': 'https://icons.veryicon.com/png/o/system/asset-management-system/unix.png',
  'ELF': 'https://cdn-icons-png.flaticon.com/512/28/28801.png',
  'Haskell': 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Haskell-Logo.svg',
  'GitHub': 'https://cdn.worldvectorlogo.com/logos/github-icon-2.svg',
  'GitHub Workflows': 'https://img.icons8.com/color/512/github-actions.png',
  'Bash': 'https://img.icons8.com/color/512/bash.png',
  'MakeFile': 'https://static-00.iconduck.com/assets.00/makefile-icon-2048x1831-10j9gh4v.png',
  'CMake': 'https://static-00.iconduck.com/assets.00/cmake-icon-2046x2048-9cd81awg.png',
  'HTML' : 'https://upload.wikimedia.org/wikipedia/commons/6/61/HTML5_logo_and_wordmark.svg',
  'CSS': 'https://upload.wikimedia.org/wikipedia/commons/d/d5/CSS3_logo_and_wordmark.svg',
  'JavaScript' : 'https://upload.wikimedia.org/wikipedia/commons/6/6a/JavaScript-logo.png',
  'React': 'https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg',
  'TailwindCSS': 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Tailwind_CSS_Logo.svg',
};